#author :GalirusOFFICIAL
#pesan : JANGAN NGRECODE ANJENG MIKIR COG
#note : Jangan Di ubah Nanti ERROR





z="
";yBz='pt"';CBz='║║╔═';XDz='hani';lDz='gem ';aBz='stal';KCz='a su';KFz='p 1';wEz='d';Yz='bl="';JBz='╔╗║║';SEz='txt';cDz='dome';lz='   ╔';lBz='Tool';EDz='rade';OEz='-r r';WDz=' mec';LFz='MEMB';SCz='geny';LDz=' bas';wDz='HOME';VEz='7 RE';qz=' ║║ ';hBz='\n  ';jEz='grad';iz='$m"╔';CDz='-y';rCz='INST';pDz='l -y';uBz='Term';XCz='tik$';Lz='"sle';cBz='ckag';Mz='ep 3';DFz='figl';tBz='una ';bDz='ypto';NBz='═╝║║';MBz='╔╗║╔';sCz='ALL$';oz='"║╔╗';QFz=' BEN';Gz=' 1"';Fz='leep';Ez='s="s';qEz=' php';LCz='dah ';xEz=' tqd';IDz='hon3';cEz=' "ap';eCz='"[GA';jBz='guna';TBz='╝"';GEz='/Gal';pCz='" ]';nBz='i"';GFz='unzi';mEz='on3 ';GCz='R$k ';yCz=' apt';dCz=' -p ';sz='║"';SBz='╝╚╝╚';VBz='════';qDz=' fig';UBz='$b"╔';dDz='rich';RDz='pip ';WCz='n ke';EEz='thub';DEz='//gi';bBz='l Pa';NFz='S"';BBz='╝║╔╗';JFz=' ]';BEz='e ht';ACz=' jik';IEz='404/';BFz='ruby';UFz='fi';oDz=' cur';XBz='b"';sEz=' wge';yDz='git ';Hz='ss="';hCz='4]==';gCz='S-40';LEz='cd T';ez='clea';az='[1;3';mBz='s In';eEz='apt ';FDz=' ins';fDz='oard';iEz='t up';eDz='keyb';Pz='033[';kz='    ';yEz='m';Dz='cho"';ICz='k$m ';bCz='h"';YEz='elif';aEz='$apa';Tz='1;32';Wz='b="\';rDz='let';mCz=' "$a';AFz='pkg ';LBz='╔╗╗║';rBz='da p';DBz='╝║╚╝';kCz='h';GBz='╣"';aDz='pycr';FFz='zip ';oBz='$k "';ZDz='s4';dz='1;37';xBz='$m a';ABz='"║╔═';AEz='clon';iCz='=> "';qCz='then';TEz='chmo';Jz='p 2"';oEz='on -';lEz='pyth';gEz='te &';JCz='sudo';uDz='ip -';pBz=' Jik';UEz='d 77';oCz=' = "';YCz='m n"';OCz='engi';GDz='tall';jCz=' apa';PEz='equi';VDz='ests';HCz='keti';tz='"║╚╝';CEz='tps:';Cz='e="e';lCz='if [';PBz='"╚╝ ';jDz=' rub';Az='q="-';KBz='╚═╗║';nCz='pah"';REz='nts.';tDz=' unz';kBz='kan ';tEz='t -y';XEz='./RE';pEz='bash';vz='╗╔══';uz='║╔══';MFz='UKA ';yz='╗"';gBz='Baru';xDz='cd';NCz='ah m';IFz=' "n"';Sz='h="\';ODz='t wg';qBz='a an';FEz='.com';DDz=' upg';UDz='requ';bz='6m"';gDz='colo';WBz='══╗$';Vz='1;33';TFz='A"';Oz='m="\';kDz='y -y';pz='║   ';MDz='h ph';eBz='lu J';YBz='$bl"';WEz='ADME';fz='r';BCz='una$';UCz=' sil';vCz='/PAC';rEz=' git';FBz='║║║═';nEz='on2 ';PCz='nsta';Iz='slee';EFz='et';JDz='hon2';ZEz=' [ "';wBz='etik';ZBz='  In';ZCz='$b"╚';xCz='p 2';QDz='y';Bz='e"';sDz=' zip';mDz='lolc';sBz='engg';NDz='p gi';YDz='ze b';TCz='a\n ';kEz='e -y';QCz='ll p';OFz='else';vBz='ux K';jz='══╗ ';bEz='h" =';RBz='╝╚══';Zz='\033';uEz=' key';iBz='Meng';aCz='══╝$';HEz='irus';CFz='curl';fBz='ika ';EBz='║╚═╗';CCz='b Li';DCz='nux/';dBz='e Du';BDz='ate ';MCz='pern';SFz='SINY';ECz='NETH';wz='╗║║╔';PDz='et -';RFz='ER I';Kz='sss=';KEz='SV3';TDz='all ';SDz='inst';nz='══╗"';HDz=' pyt';Rz='m"';cz='p="\';dEz='t" ]';RCz='acka';fCz='LIRU';MEz='OOLS';QBz=' ╚╝╚';JEz='TOOL';VCz='ahka';HFz='p -y';vDz='cd $';vEz='boar';NEz='V4';HBz='$p"║';cCz='read';fEz='upda';mz='╗   ';Qz='1;31';tCz='h MO';hz=' $q ';FCz='UNTE';OBz='║═╣"';QEz='reme';uCz='DULE';IBz='║  ║';Xz='1;34';iDz='tqdm';nDz='at';Nz='"';KDz=' -y';gz='echo';Uz='k="\';hDz='rama';ADz=' upd';hEz='& ap';wCz='KAGE';rz=' ║╔╗';xz='╗║╚╝';PFz='YANG';
eval "$Az$Bz$z$Cz$Dz$z$Ez$Fz$Gz$z$Hz$Iz$Jz$z$Kz$Lz$Mz$Nz$z$Oz$Pz$Qz$Rz$z$Sz$Pz$Tz$Rz$z$Uz$Pz$Vz$Rz$z$Wz$Pz$Xz$Rz$z$Yz$Zz$az$bz$z$cz$Pz$dz$Rz$z$ez$fz$z$gz$hz$iz$jz$kz$lz$mz$lz$nz$z$gz$hz$oz$pz$kz$qz$kz$rz$sz$z$gz$hz$tz$uz$vz$wz$vz$xz$uz$yz$z$gz$hz$ABz$BBz$CBz$DBz$BBz$EBz$FBz$GBz$z$gz$hz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$z$gz$hz$PBz$QBz$RBz$SBz$SBz$RBz$RBz$TBz$z$gz$z$gz$hz$UBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$WBz$XBz$z$gz$z$gz$hz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$z$gz$hz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$z$gz$hz$oBz$ACz$qBz$rBz$sBz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$Nz$z$gz$hz$oBz$ACz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$TCz$UCz$VCz$WCz$XCz$YCz$z$gz$z$gz$hz$ZCz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$aCz$bCz$z$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$z$lCz$mCz$nCz$oCz$JCz$pCz$z$qCz$z$gz$hz$oBz$rCz$sCz$tCz$uCz$vCz$wCz$Nz$z$Iz$xCz$z$JCz$yCz$ADz$BDz$CDz$z$JCz$yCz$DDz$EDz$z$JCz$yCz$FDz$GDz$HDz$IDz$HDz$JDz$KDz$z$JCz$yCz$FDz$GDz$LDz$MDz$NDz$ODz$PDz$QDz$z$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$z$RDz$SDz$TDz$aDz$bDz$cDz$z$RDz$SDz$TDz$dDz$z$RDz$SDz$TDz$eDz$fDz$z$RDz$SDz$TDz$gDz$hDz$z$RDz$SDz$TDz$iDz$z$JCz$yCz$FDz$GDz$jDz$kDz$z$lDz$SDz$TDz$mDz$nDz$z$JCz$yCz$FDz$GDz$oDz$pDz$z$JCz$yCz$FDz$GDz$qDz$rDz$z$JCz$yCz$FDz$GDz$sDz$KDz$z$JCz$yCz$FDz$GDz$tDz$uDz$QDz$z$vDz$wDz$z$xDz$z$yDz$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$z$xDz$z$LEz$MEz$NEz$z$RDz$SDz$TDz$OEz$PEz$QEz$REz$SEz$z$TEz$UEz$VEz$WEz$z$XEz$WEz$z$YEz$ZEz$aEz$bEz$cEz$dEz$z$qCz$z$eEz$fEz$gEz$hEz$iEz$jEz$kEz$z$eEz$SDz$TDz$lEz$mEz$lEz$nEz$lEz$oEz$QDz$z$eEz$SDz$TDz$pEz$qEz$rEz$sEz$tEz$z$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$z$RDz$SDz$TDz$aDz$bDz$cDz$z$RDz$SDz$TDz$dDz$uEz$vEz$wEz$z$RDz$SDz$TDz$gDz$hDz$xEz$yEz$z$AFz$SDz$TDz$BFz$KDz$z$lDz$SDz$TDz$mDz$nDz$z$AFz$SDz$TDz$CFz$KDz$z$AFz$SDz$TDz$DFz$EFz$z$AFz$SDz$TDz$FFz$CDz$z$AFz$SDz$TDz$GFz$HFz$z$vDz$wDz$z$xDz$z$yDz$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$z$xDz$z$LEz$MEz$NEz$z$RDz$SDz$TDz$OEz$PEz$QEz$REz$SEz$z$TEz$UEz$VEz$WEz$z$XEz$WEz$z$YEz$ZEz$aEz$bEz$IFz$JFz$z$qCz$z$Iz$KFz$z$gz$hz$oBz$LFz$MFz$JEz$NFz$z$Iz$xCz$z$vDz$wDz$z$xDz$z$LEz$MEz$NEz$z$TEz$UEz$VEz$WEz$z$XEz$WEz$z$OFz$z$gz$hz$oBz$PFz$QFz$RFz$SFz$TFz$z$Iz$xCz$z$UFz"